### ISSUE TITLE
int too big to convert

### ISSUE THREAD

**Issue by duckYcy** [FeeeeK/CEFunctionDecoder#1]
`Traceback (most recent call last):`
`  File "D:\a\decode_function.py", line 148, in <module>`
`    lua_bytecode = lua_decode_function(encoded_str)`
`                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "D:\a\decode_function.py", line 39, in lua_decode_function`
`    decoded_bytes = CustomBase85.base85_to_bin(encoded_str)`
`                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "D:\a\decode_function.py", line 28, in base85_to_bin`
`    result.extend(a.to_bytes(4, "big"))`
`                  ^^^^^^^^^^^^^^^^^^^^`
`OverflowError: int too big to convert`

any solutions😭?

**Comment by axd1x8a** [comment]
@duckYcy can you provide an example of the table you are trying to decode?

**Comment by duckYcy** [comment]
> @duckYcy can you provide an example of the table you are trying to decode?

https://gofile.io/d/W6W5ik
here you go

**Comment by FeeeeK** [comment]
Hi, sorry for the late reply, can you send the file or link to the file to ce@axd1x8a.me? I'll see what's wrong.

**Comment by axd1x8a** [comment]
Hi, sorry for the late reply, it seems that there is something weird with this file and encoded string is not in base85
