### ISSUE TITLE
Error when decompiling lua file

### ISSUE THREAD

**Issue by Taffy-Nyaru** [FeeeeK/CEFunctionDecoder#2]
I used luadec to decompile the decoded.luac file and this comes out, i think it should be the CE decoder's problem becasue the encoded string is more than 9000 chars, so i put it into a txt to decode it again however still catching errors.
p.s. I checked with another encoded string and it works in a txt file, so it's rather possibly the problem of the CE decoder.

The encoded string is private so can I contact you to send it?
parse luac: Error(
    Stack {
        base: Alt(
            [
                Base {
                    location: 5206,
                    kind: Kind(
                        Tag,
                    ),
                },
                Base {
                    location: 5206,
                    kind: Kind(
                        Tag,
                    ),
                },
                Base {
                    location: 5206,
                    kind: Kind(
                        Tag,
                    ),
                },
                Base {
                    location: 5206,
                    kind: Kind(
                        Tag,
                    ),
                },
                Base {
                    location: 5206,
                    kind: Kind(
                        Tag,
                    ),
                },
                Base {
                    location: 5206,
                    kind: Kind(
                        Tag,
                    ),
                },
            ],
        ),
        contexts: [
            (
                2614,
                Kind(
                    Count,
                ),
            ),
            (
                2610,
                Context(
                    "count constants",
                ),
            ),
            (
                46,
                Context(
                    "chunk",
                ),
            ),
        ],
    },
)

**Comment by FeeeeK** [comment]
Hi, send a link to the ce table to ce@axd1x8a.me and I'll take a look

**Comment by axd1x8a** [comment]
I replied in an e-mail, but I'll repeat here as well:
The luadec fork mentioned in the readme works fine, I recommend using it if you have any decompilation issues
